from collections.abc import Iterator
from typing import Self, final

__all__ = ["ListPortInfo", "comports"]

@final
class ListPortInfo:
    device: str
    name: str
    description: str
    hwid: str
    vid: int | None
    pid: int | None
    serial_number: str | None
    location: str | None
    manufacturer: str | None
    product: str | None
    interface: str | None
    def __new__(cls, device: str, skip_link_detection: bool = False) -> Self: ...
    def usb_description(self) -> str: ...
    def usb_info(self) -> str: ...
    def apply_usb_info(self) -> None: ...
    def __getitem__(self, index: int, /) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

def comports(include_links: bool = False) -> list[ListPortInfo]: ...
