[package]
name = "oxiserial"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "oxiserial"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.29", features = ["abi3-py311"] }
serialport = { version = "4.10", default-features = false, features = ["usbportinfo-location"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "time", "sync", "macros"] }
tokio-serial = "5.5"

[target.'cfg(target_os = "linux")'.dependencies]
nix = { version = "0.31", features = ["term"] }

[target."cfg(unix)".dependencies]
libc = "0.2.189"

[target."cfg(windows)".dependencies]
windows-sys = { version = "0.61", features = ["Win32_Devices_Communication", "Win32_Foundation"] }

[dev-dependencies]
tokio = { version = "1.53.1", features = ["test-util", "macros", "rt"] }

[features]
test-backend = []
