from oxiserial.aio import Future

__all__ = ["mock_pair", "mock_block_writes", "mock_state", "delayed"]

def mock_pair() -> tuple[str, str]: ...
def mock_block_writes(port: str, blocked: bool) -> None: ...
def mock_state(port: str) -> dict[str, int | bool]: ...
def delayed(value: bytes, delay: float) -> Future[bytes]: ...
