from collections.abc import Generator
from typing import Any, Generic, TypeVar, final

__all__ = ["Future"]

_T_co = TypeVar("_T_co", covariant=True)

@final
class Future(Generic[_T_co]):
    def wait(self, timeout: float | None = None) -> _T_co: ...
    def done(self) -> bool: ...
    def cancel(self) -> bool: ...
    def result(self) -> _T_co: ...
    def __await__(self) -> Generator[Any, None, _T_co]: ...
    def __class_getitem__(cls, key: Any) -> Any: ...
